// src/lib/pages/login/LoginPage.svelte
<script lang="ts">
    import Alert from '@/components/Alert.svelte';
    import Column from '@/components/Column.svelte';
    import TextField from '@/components/inputs/TextField.svelte';
    import type { AuthContext } from '@/auth/types';
    import type { NavContext } from '@/router/types';
    import { Button } from 'bits-ui';
    import { getContext } from 'svelte';
    import { getUserByUsername, verifyPassword } from '@/api/users';
    import { toCssString } from '@/utils/cssHelpers';
    import AlertBox from '@/components/AlertBox.svelte';
    import { loadEndpoint } from '@/api/network';

    const { authorize } = getContext<AuthContext>('authContext');
    const { navigateTo } = getContext<NavContext>('navContext');

    /** State of the username input. */
    let usernameState = $state({
        input: '',
        isValid: true,
    });

    /** State of the password input. */
    let passwordState = $state({
        input: '',
        isValid: true,
    });

    /** Determines if the input is being validated. */
    let isValidating = $state(false);

    /** List of validation errors. */
    let validationErrors = $state<string[]>([]);

    /** Deduplicated version of [validationErrors]. */
    let uniqueErrors = $derived([...new Set(validationErrors)]);

    /** Style for the validation alerts. */
    const alertStyle = toCssString({
        width: '15em',
    });

    /** Style for the entire form. */
    const formStyle = toCssString({
        justifyContent: 'center',
        alignItems: 'center',
    });

    /** Validates the login (username and password). */
    async function validateAndLogin() {
        isValidating = true;

        // Validate username
        const user = await getUserByUsername(usernameState.input);
        if (!user) {
            usernameState.isValid = false;
            isValidating = false;
            validationErrors = [...validationErrors, 'Username not found!'];
            return;
        }

        // Validate password
        const passwordVerified = await verifyPassword(
            user.id,
            passwordState.input
        );
        if (!passwordVerified) {
            passwordState.isValid = false;
            isValidating = false;
            validationErrors = [...validationErrors, 'Incorrect password!'];
            return;
        }

        usernameState.isValid = true;
        passwordState.isValid = true;
        validationErrors = [];

        // Authorize user
        authorize(user);

        // Load network endpoint
        loadEndpoint(user.id);

        // Go to dashboard
        isValidating = false;
        await navigateTo('/dashboard', { replace: true });
    }
</script>

<Column spacing="2em" style={formStyle}>
    <h1 class="app-title">Spots</h1>

    <!-- Form -->
    <TextField
        label="Username"
        bind:value={usernameState.input}
        invalid={!usernameState.isValid}
        required
        oninput={() => {
            if (!usernameState.isValid) {
                usernameState.isValid = true;
                validationErrors = [];
            }
        }}
    />
    <TextField
        bind:value={passwordState.input}
        invalid={!passwordState.isValid}
        label="Password"
        type="password"
        required
        oninput={() => {
            if (!passwordState.isValid) {
                passwordState.isValid = true;
                validationErrors = [];
            }
        }}
    />
    <Button.Root onclick={validateAndLogin}>
        {#if isValidating}
            Logging in...
        {:else}
            Login
        {/if}
    </Button.Root>

    <!-- Navigate to `Sign up` -->
    <Button.Root
        href="#"
        onclick={async (e) => {
            e.preventDefault();
            await navigateTo('/signup');
        }}>Sign up</Button.Root
    >

    <!-- Error messages -->
    <AlertBox
        style="transform: translateY(22em);"
        {alertStyle}
        alerts={uniqueErrors.map((text) => ({
            level: 'error',
            text,
        }))}
    />
</Column>

<style>
    .app-title {
        margin-bottom: 3em;
        margin-top: -1em;
        padding-top: 0;
    }
</style>

// src/pages/login/LoginPage.tsx
import Banner from '@/components/banner/Banner';
import Container from '@/components/Container';
import useTransitionNavigate from '@/utils/hooks/useTransitionNavigate';
import { Alert, CircularProgress, Stack, styled } from '@mui/material';
import { Form } from 'react-router-dom';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { StyledButton, StyledTextField } from '@/components/form/styled';
import { useAtomValue } from 'jotai';
import { authContextActionAtom, authContextAtom } from '@/utils/auth/atoms';
import { verifyPassword } from '@/api/users';
import { loadEndpointAtom } from '@/utils/network/atoms';
import { getUserAtom } from '@/utils/users/atoms';

export default function LoginPage() {
    const transitionNavigate = useTransitionNavigate();
    const { isLoading } = useAtomValue(authContextAtom);
    const { authorize } = useAtomValue(authContextActionAtom);
    const loadEndpoint = useAtomValue(loadEndpointAtom);

    // Form input states
    const [usernameInput, setUsernameInput] = useState('');
    const userAtom = useMemo(() => {
        return getUserAtom({ type: 'username', value: usernameInput });
    }, [usernameInput]);
    const user = useAtomValue(userAtom).data;

    // Validation states
    const [isValid, setIsValid] = useState({ username: true, password: true });
    const [errMsg, setErrMsg] = useState<string[]>([]);
    const [validating, setValidating] = useState(false);
    const isBusy = isLoading || loadEndpoint.isPending || validating;

    /* Reset validation on unmount */
    useEffect(() => {
        return () => {
            setIsValid({ username: true, password: true });
            setErrMsg([]);
            setValidating(false);
        };
    }, []);

    /** Validates the username and password, then redirects to the dashboard. */
    async function validateLoginAndRedirect(e: FormEvent<HTMLFormElement>) {
        e.preventDefault();
        setValidating(true);

        const formData = new FormData(e.currentTarget);
        const username = formData.get('username');
        const password = formData.get('password');

        if (typeof username === 'string' && typeof password === 'string') {
            // Validate username
            if (!user) {
                setIsValid((prev) => ({
                    username: false,
                    password: prev.password,
                }));
                setErrMsg((prev) => [...prev, 'Username not found!']);
                setValidating(false);
                return;
            }

            // Validate password
            const verified = await verifyPassword(user.id, password);
            if (!verified) {
                setIsValid((prev) => ({
                    username: prev.username,
                    password: false,
                }));
                setErrMsg((prev) => [...prev, 'Incorrect password!']);
                setValidating(false);
                return;
            }

            setIsValid({ username: true, password: true });
            setErrMsg([]);

            // Authorize username
            await authorize(username);

            // Load network endpoint
            await loadEndpoint.mutateAsync(user.id);

            // Go to homepage
            setValidating(false);
            await transitionNavigate('/dashboard', { replace: true });
        }
    }

    return (
        <StyledContainer direction="column">
            <Banner />

            {/* Login form */}
            <Form onSubmit={validateLoginAndRedirect}>
                <Stack spacing="1em" direction="column">
                    <StyledTextField
                        label="Username"
                        name="username"
                        type="text"
                        placeholder="Enter username..."
                        fullWidth
                        required
                        error={!isValid.username}
                        onChange={(e) => {
                            setUsernameInput(e.currentTarget.value);
                            if (!isValid.username) {
                                setIsValid((prev) => ({
                                    username: true,
                                    password: prev.password,
                                }));
                                setErrMsg([]);
                            }
                        }}
                    />
                    <StyledTextField
                        label="Password"
                        name="password"
                        type="password"
                        placeholder="Enter password..."
                        fullWidth
                        required
                        error={!isValid.password}
                        onChange={(_) => {
                            if (!isValid.password) {
                                setIsValid((prev) => ({
                                    username: prev.username,
                                    password: true,
                                }));
                                setErrMsg([]);
                            }
                        }}
                    />

                    <div style={{ textAlign: 'center' }}>
                        <StyledButton
                            type="submit"
                            variant="contained"
                            disabled={isBusy}
                            color="primary"
                        >
                            {validating ? 'Logging in...' : 'Login'}
                        </StyledButton>
                    </div>
                    <div
                        style={{
                            textAlign: 'center',
                        }}
                    >
                        {validating ? <CircularProgress /> : null}
                    </div>
                </Stack>
            </Form>

            {/* Sign up link */}
            <a
                href="#"
                style={{ marginTop: '-4em' }}
                onClick={(e) => {
                    e.preventDefault();
                    if (!validating) {
                        transitionNavigate('/signup');
                    }
                }}
            >
                Sign Up
            </a>

            {/* Error alerts */}
            <Stack gap={'1em'}>
                {errMsg.map((msg) => (
                    <Alert severity="error" variant="filled" key={msg}>
                        {msg}
                    </Alert>
                ))}
            </Stack>
        </StyledContainer>
    );
}

const StyledContainer = styled(Container)({
    textAlign: 'center',
    justifyContent: 'center',
});
