// src/components/Column.tsx
import { JSX } from 'solid-js';

/** A column container. */
export function Column(props: { children?: any; style?: JSX.CSSProperties }) {
  const { children, style } = props;
  const baseStyle: JSX.CSSProperties = {
    display: 'flex',
    'flex-direction': 'column',
    gap: '2em',
  };
  return <div style={{ ...baseStyle, ...style }}>{children}</div>;
}

// src/lib/components/ui/Column.svelte
<script lang="ts">
  import type { RestProps } from '@/utils/restProps';

  type Props = {
    class?: string;
    style?: string;
    spacing?: string;
  } & RestProps;

  const {
    class: className,
    style,
    spacing = '0.1em',
    children,
    ...restProps
  }: Props = $props();

  const combinedClass = `col ${className}`;

  const combinedStyle = `gap: ${spacing}; ${style}`;
</script>

<div class={combinedClass} style={combinedStyle} {...restProps}>
  {@render children()}
</div>

<style>
  .col {
    display: flex;
    flex-direction: column;
    box-sizing: border-box;
  }
</style>
