// src/lib/components/Row.svelte
<script lang="ts">
    const {
        spacing = '0.1em',
        class: className = '',
        children,
        style = '',
        ...restProps
    } = $props();
</script>

<div class="row {className}" style="gap: {spacing}; {style}" {...restProps}>
    {@render children()}
</div>

<style>
    .row {
        display: flex;
        flex-direction: row;
        width: 100%;
        height: 100%;
    }
</style>

// src/components/Row.tsx
import { JSX } from 'solid-js';

/** A row container. */
export function Row(props: { children?: any; style?: JSX.CSSProperties }) {
  const { children, style } = props;
  const baseStyle: JSX.CSSProperties = {
    display: 'flex',
    'flex-direction': 'row',
    gap: '2em',
  };
  return <div style={{ ...baseStyle, ...style }}>{children}</div>;
}
